### ISSUE TITLE
botoy中为什么发消息只能限定2个字符以内？

### ISSUE THREAD

**Issue by qizhao-umbc** [opq-osc/bbb_bot#1]
作者您好，抱歉没在botoy那个页面发issue，因为在那个仓库里我找不到可以发issue的地方。
我的问题是，在机器人发送消息的时候，消息的长度似乎只能小于等于 2个字符
“ok” 机器人是可以发出来的，但是 ok1 就发不出来了

@bot.on_group_msg
def group(ctx: GroupMsg):
    if ctx.FromUserId != ctx.CurrentQQ and ctx.Content == '你好':
        Action(ctx.CurrentQQ).sendGroupText(ctx.FromGroupId,"nii")

nii为三个字符，就发不出来。

请问有什么办法可以让机器发送超过两个字符的消息吗？ 感谢您开发出这么棒的框架！

**Comment by qizhao-umbc** [comment]
似乎中文也是发不出来的

**Comment by BrandTime** [comment]
尝试添加 atUser=0

**Comment by qizhao-umbc** [comment]
你好，这个问题似乎只在在群内发送消息的时候出现，在私聊的时候没有出现

**Comment by BrandTime** [comment]
尝试添加 atUser=0

**Comment by qizhao-umbc** [comment]
我尝试添加了atUser = 0 似乎也不行..
代码类似这样

@bot.on_group_msg
def group(ctx: GroupMsg):
    if ctx.FromUserId != ctx.CurrentQQ and ctx.Content == 'test':
        Action(ctx.CurrentQQ).sendGroupText(432455,'testststst',atUser=0)

**Comment by BrandTime** [comment]
看代码示例 bbb_bot/plugins/bot_revoke.py

**Comment by qizhao-umbc** [comment]
好的，感谢!
