### ISSUE TITLE
带佬好，plugins文件夹里的py插件可以放到自己机器人里用吗？

### ISSUE THREAD

**Issue by sayri23** [opq-osc/bbb_bot#3]
如题，我把早安那个py文件放自己机器人里之后再运行会报错了，之后把resources王文件夹放进去了也不行

**Comment by sayri23** [comment]
No module named 'util'

**Comment by sayri23** [comment]
![Screenshot_2021-04-04-21-02-39-22_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/62638560/113509656-61df1480-9589-11eb-9b1d-5ba9c03d8a4f.jpg)

**Comment by BrandTime** [comment]
那个用到了mysql数据库存储数据，要移植 bot_good_morning.py 插件遵循以下步骤。
1. 建立数据库，（见database.sql -> tb_good_morning表）
2. 复制 util/db 目录结构和所有文件。
3. 配置数据库连接信息（mysql.json）
4. 基本完成移植操作，当然不排除可能出现的其他错误。因此，最好要有基本的python知识。

**Comment by BrandTime** [comment]
如果实在感觉繁琐，可以使用[opqqq-plugin](https://github.com/fz6m/opqqq-plugin)的早安插件，我改写的他的，将他的文件存储改为了数据库存储，并简化了他的代码。你可以直接复制他的，但是他用的是iotbot，可能还是要修改部分代码。

**Comment by sayri23** [comment]
好的，谢谢
